Updated front end
nesh325/TClone pull request #2
Opened 2021-07-12 13:49 UTC by nesh325

2021-07-20 17:00 UTC, Sumit-Kap commented on Client/src/App.js
> +      <Router>
Here we could create an array of routes to make it scalable where on addition of routes only entry in that array should be updated else would be kept intact something like this 

const routes = [
	{ path: '/', component: HomeView, renderOnServer: true},
	{ path: '/profile', component: LoginView, renderOnServer: true},
	{ path: '/saved', component: ChatView }
]

2021-07-20 17:04 UTC, Sumit-Kap commented on Client/src/App.js
> +          <Route path="/profile">
you can also pass component prop inside your <Route/> declaration see below example. Read this https://reactrouter.com/web/api/Route
```suggestion
          <Route path="/profile" component={Profile}>
```

2021-07-20 17:12 UTC, Sumit-Kap commented on Client/src/Components/NavBar.jsx
> +  let [active, setActive] = useState(1);
can't we use an enum instead of numbers here?

2021-07-20 17:12 UTC, Sumit-Kap commented on Client/src/Components/NavBar.jsx
> +        <p className="font-roboto font-medium	text-sm ml-2">John Doe</p>
power this name through constant file.

2021-07-20 17:13 UTC, Sumit-Kap commented on Client/src/Components/NewTweet.jsx
> +      <p className="font-poppins text-sm font-medium">Tweet something</p>
power all the string values through constant file.

2021-07-20 17:17 UTC, Sumit-Kap commented on Client/src/index.js
> +ReactDOM.render(<App />, document.getElementById("app"));
This got changed in react 18, check this link https://javascript.works-hub.com/learn/react-18-is-here-whats-new-9b46a

2021-07-20 17:20 UTC, Sumit-Kap commented on node_modules/react-icons/LICENSE
> +The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
why are you checking your node_modules files here?

2021-07-20 17:24 UTC, Sumit-Kap requested changes
Please remove all your node_modules files from here. add node_modules in your .gitignore.

2021-07-20 17:25 UTC, Sumit-Kap commented on Client/src/App.js
> +      <Router>
Now use this to iterate over the routes for example.

<Switch>
				{
					routes.map((route, i)=>{
						return <Route key={i} exact path ={route.path} component={route.component} />
					})
				}
			</Switch>

2021-07-21 02:49 UTC, nesh325 commented on Client/src/App.js
> +      <Router>
Thank you, I like this approach a lot. Fixed and will update on next push

2021-07-21 14:26 UTC, nesh325 commented on Client/src/Components/NavBar.jsx
> +  let [active, setActive] = useState(1);
How would I do enums? Something like 
Something like - 

const NavLinkTitles = { Home:1, ...}

2021-07-21 14:29 UTC, nesh325 commented on Client/src/Components/NavBar.jsx
> +        <p className="font-roboto font-medium	text-sm ml-2">John Doe</p>
Do you mean to put "John Doe" in const variable?

2021-07-21 14:52 UTC, nesh325 commented on Client/src/index.js
> +ReactDOM.render(<App />, document.getElementById("app"));
`const container = document.getElementById("app");

const root = ReactDOM.createRoot(container, { hydrate: true });

root.render(<App />);`
Doesn't seem to work. Updated react to 18 as well

2021-07-21 14:52 UTC, nesh325 commented on node_modules/react-icons/LICENSE
> +The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
Removed

2021-07-21 14:54 UTC, nesh325 commented on Client/src/Components/NavBar.jsx
> +        <p className="font-roboto font-medium	text-sm ml-2">John Doe</p>
I'm not sure about this. Make a file with const text and then import and insert one by one?

2021-11-05 06:33 UTC, merged